Repository PaperStrike/Pjax, pull requests merged in 2021-10, with the labels that each got.

#187 Manually update dependencies that breaks
  package-lock.json
  package.json
  test/index.ts
  test/switchDOM.test.ts
Labels: enhancement, dependencies

#176 'exclude' option for triggers, 'receive' event
  README.md
  README.zh-Hans.md
  src/index.ts
  src/switchDOM.ts
  src/utils/DefaultTrigger.ts
Labels: enhancement, minor

#191 Use regex to match script types
  src/libs/executeScripts/Script.ts
Labels: enhancement

#192 Use case-insensitive match to parse script type
  src/libs/executeScripts/Script.ts
  test/libs/executeScripts/Script.test.ts
Labels: bug

#225 Use source-mapped onfetch
  package-lock.json
  package.json
Labels: enhancement, dependencies
